---
- name: Create Pi-hole folder on Pi.
  ansible.builtin.file:
    path: ~/pi-hole
    state: directory
    mode: 0755
  become: false

- name: Get CIDR notation of subnet
  set_fact:
    mask_cidr: "{{ ip | ipaddr('prefix') }}"
  vars:
    ip: "{{ ansible_facts['default_ipv4']['address'] }}/{{ansible_facts['default_ipv4']['netmask'] }}"

- name: CIDR subnet is
  ansible.builtin.debug:
    msg: 'Subnet: {{ mask_cidr }}'

- name: Copy Pi-hole docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/pi-hole-docker-compose.yml.j2
    dest: ~/pi-hole/docker-compose.yml
    mode: '0640'
  become: false

# TODO: The first time this playbook is run, the `pi` user may not be added
# to the `docker` group, so this task may fail.
- name: Ensure Pi-hole is running.
  community.docker.docker_compose:
    project_src: ~/pi-hole/
    build: false
  become: false
